players:
    student1:
      working_dir: ../torcs-client
      start_command: ['./start.sh', '-p', '3001', '-w', '../model.pickle', '-o', '../model_results/results']
      output_dir: ./output/
controller:
  torcs_config_file: ../config/quickrace.xml
rater:
  filename: ../ratings.csv
